apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "openpm.fullname" . }}-config
  labels:
    {{- include "openpm.labels" . | nindent 4 }}
data:
  NODE_ENV: {{ .Values.global.environment | quote }}
  CORS_ORIGIN: {{ .Values.api.corsOrigin | default (printf "http://%s" .Values.global.domain) | quote }}
  
  # Frontend environment variables
  {{- $proto := "http" }}
  {{- $wsProto := "ws" }}
  {{- if .Values.ingress.tls }}
    {{- $proto = "https" }}
    {{- $wsProto = "wss" }}
  {{- end }}
  NEXT_PUBLIC_API_URL: {{ printf "%s://%s/api" $proto .Values.global.domain | quote }}
  NEXT_PUBLIC_WS_URL: {{ printf "%s://%s/ws" $wsProto .Values.global.domain | quote }}
  PORT: {{ .Values.frontend.port | default 3001 | quote }}
