apiVersion: v1
kind: Secret
metadata:
  name: {{ include "openpm.fullname" . }}-secrets
  labels:
    {{- include "openpm.labels" . | nindent 4 }}
type: Opaque
data:
  JWT_SECRET: {{ .Values.secrets.jwtSecret | b64enc | quote }}
  
  DATABASE_URL: {{ if .Values.postgres.enabled }}
    {{- printf "postgresql://%s:%s@%s:5432/%s" .Values.secrets.postgres.username .Values.secrets.postgres.password (include "openpm.postgres.fullname" .) .Values.secrets.postgres.database | b64enc | quote }}
  {{- else }}
    {{- .Values.externalDatabase.url | b64enc | quote }}
  {{- end }}

  REDIS_URL: {{ if .Values.redis.enabled }}
    {{- printf "redis://:%s@%s:6379/0" .Values.secrets.redis.password (include "openpm.redis.fullname" .) | b64enc | quote }}
  {{- else }}
    {{- .Values.externalRedis.url | b64enc | quote }}
  {{- end }}

  # Self-hosted Postgres credentials (if enabled)
  {{- if .Values.postgres.enabled }}
  POSTGRES_USER: {{ .Values.secrets.postgres.username | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.secrets.postgres.password | b64enc | quote }}
  POSTGRES_DB: {{ .Values.secrets.postgres.database | b64enc | quote }}
  {{- end }}

  # Self-hosted Redis credentials (if enabled)
  {{- if .Values.redis.enabled }}
  REDIS_PASSWORD: {{ .Values.secrets.redis.password | b64enc | quote }}
  {{- end }}
